# Generated by Django 3.1 on 2020-08-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workmateapp', '0002_employee_dogg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dogg',
        ),
    ]
