# Generated by Django 3.1 on 2020-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmateapp', '0003_remove_employee_dogg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('job_name', 'company')},
            },
        ),
    ]
