# Generated by Django 3.1 on 2020-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmateapp', '0004_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(related_name='employees', to='workmateapp.Job'),
        ),
    ]
